<?php
/**
 * This file has been automaticaly generated by Pomm Cli package.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\Base\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Snippet
 *
 * Structure class for relation public.snippet.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Snippet extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('public.snippet')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('author_id', 'int4')
            ->addField('keywords', 'varchar[]')
            ->addField('title', 'varchar')
            ->addField('codes', 'public.source[]')
            ->addField('created', 'timestamp')
            ->addField('updated', 'timestamp')
            ;
    }
}
